name: Deploy Python Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - 'requirements.txt'
      - '.github/workflows/deploy-server.yml'
  workflow_dispatch:

jobs:
  test:
    name: Test Python Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test server imports
        run: |
          python -c "from server.game_server import GameState, Player, Bullet; print('Server imports successfully')"

      - name: Check server can start (dry run)
        run: |
          timeout 5s python server/game_server.py || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
          echo "Server started successfully"

  deploy-render:
    name: Deploy to Render (Optional)
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Render
        if: ${{ secrets.RENDER_DEPLOY_HOOK_URL != '' }}
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          echo "Deployment triggered on Render.com"
        continue-on-error: true

      - name: Deployment instructions
        run: |
          echo "=========================================="
          echo "Python Server Deployment Instructions"
          echo "=========================================="
          echo ""
          echo "The server code has been tested successfully!"
          echo ""
          echo "To deploy your server, choose one of these options:"
          echo ""
          echo "1. RENDER.COM (Recommended for auto-deployment via GitHub Actions):"
          echo "   - Create a Web Service on https://render.com"
          echo "   - Connect your GitHub repository"
          echo "   - Set Build Command: pip install -r requirements.txt"
          echo "   - Set Start Command: python server/game_server.py"
          echo "   - Copy the Deploy Hook URL from Settings"
          echo "   - Add it as a secret 'RENDER_DEPLOY_HOOK_URL' in your GitHub repo"
          echo "   - Future pushes will automatically deploy!"
          echo ""
          echo "2. RAILWAY.APP (Easiest setup):"
          echo "   - Visit https://railway.app"
          echo "   - Click 'New Project' → 'Deploy from GitHub repo'"
          echo "   - Select your repository"
          echo "   - Railway auto-detects Python and deploys automatically"
          echo ""
          echo "3. FLY.IO (Best for global distribution):"
          echo "   - Install flyctl: https://fly.io/docs/hands-on/install-flyctl/"
          echo "   - Run: flyctl launch"
          echo "   - Configure and deploy: flyctl deploy"
          echo ""
          echo "4. HEROKU (Classic platform):"
          echo "   - Install Heroku CLI: https://devcenter.heroku.com/articles/heroku-cli"
          echo "   - Create Procfile: web: python server/game_server.py"
          echo "   - Run: heroku create && git push heroku main"
          echo ""
          echo "=========================================="
          echo "After deployment, update static/config.js with your server URL!"
          echo "=========================================="

  build-info:
    name: Build Information
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display deployment information
        run: |
          echo "## Deployment Information" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Server tests passed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Server Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Port**: Configurable via PORT environment variable (default: 8080)" >> $GITHUB_STEP_SUMMARY
          echo "- **Dependencies**: aiohttp, websockets" >> $GITHUB_STEP_SUMMARY
          echo "- **Python Version**: 3.7+" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Quick Deploy Options" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Option 1: Render.com (Recommended)" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "1. Go to https://render.com" >> $GITHUB_STEP_SUMMARY
          echo "2. New → Web Service" >> $GITHUB_STEP_SUMMARY
          echo "3. Connect GitHub repo: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "4. Build Command: pip install -r requirements.txt" >> $GITHUB_STEP_SUMMARY
          echo "5. Start Command: python server/game_server.py" >> $GITHUB_STEP_SUMMARY
          echo "6. Deploy!" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Option 2: Railway.app" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "1. Go to https://railway.app" >> $GITHUB_STEP_SUMMARY
          echo "2. New Project → Deploy from GitHub" >> $GITHUB_STEP_SUMMARY
          echo "3. Select repository: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
          echo "4. Auto-deploys!" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Automatic Deployment with Render.com" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "To enable automatic deployment via GitHub Actions:" >> $GITHUB_STEP_SUMMARY
          echo "1. Create your Web Service on Render.com" >> $GITHUB_STEP_SUMMARY
          echo "2. Go to Settings → Deploy Hook" >> $GITHUB_STEP_SUMMARY
          echo "3. Copy the Deploy Hook URL" >> $GITHUB_STEP_SUMMARY
          echo "4. Add it as a GitHub secret named \`RENDER_DEPLOY_HOOK_URL\`" >> $GITHUB_STEP_SUMMARY
          echo "5. Push to main branch - deployment happens automatically!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### After Deployment" >> $GITHUB_STEP_SUMMARY
          echo "Update \`static/config.js\` with your server URL:" >> $GITHUB_STEP_SUMMARY
          echo '```javascript' >> $GITHUB_STEP_SUMMARY
          echo "window.GAME_CONFIG = {" >> $GITHUB_STEP_SUMMARY
          echo "  wsUrl: 'wss://your-server-url.onrender.com/ws'," >> $GITHUB_STEP_SUMMARY
          echo "};" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📚 Full documentation: [GITHUB_ACTIONS_DEPLOYMENT.md](https://github.com/${{ github.repository }}/blob/main/GITHUB_ACTIONS_DEPLOYMENT.md)" >> $GITHUB_STEP_SUMMARY
